### PR TITLE
Store current gameweek and fetch it when going to fixture list page

### PR DESCRIPTION
**Pull request by HoinzeyBear**
Store current gameweek and fetch it when going to fixture list page s…o you view current gameweek's fixtures.

One issue is that as the call to `loadData` takes so long, you can enter the fixtures page before this value has been set, landing you on GW1 rather than the current GW. 

Not sure if we want to explore ways around that ?

### CODE REVIEW

**Comment by joreilly** [comment]
Could `currentGameweek` be made say a `StateFlow` and UI/ViewModel etc would collect it...so even if it started off at game week 1 it would switch then to current one once it got the data?

**Comment by joreilly** [comment]
Ideally also we'd return single UI state for particular screen (I also probably need to split in to separate view models per screen) so perhaps in this case that would be combination of the current game week and associated fixtures....and that might then give us option to ensure "consistent" data was combined and made available to UI once all data needed was available.  Anyway, something perhaps for another day :)

**Comment by HoinzeyBear** [comment]
I originally had it as a StateFlow but then you can get a scenario of jank where you are on GW1 and then it pops to GW8 which isn't the nicest UX. 

What about some indicator on Repository to say it has completed loading the data or not ? 
Might be handy in a few places, you could show a sort of low-fidelity version of the screen while waiting for the real data to fill it in

**Comment by joreilly** [comment]
Yeah, something like that could definitely be useful...or just even just to show progress spinner there while waiting.

**Comment by HoinzeyBear** [comment]
OK, will close this for now and can work on sorting out some of the bits mentioned above.

**Pull request closed without merging**
