### PR TITLE
Update Room version to 2.7.0-alpha07

### PR DESCRIPTION
**Pull request by zsmb13**
Updated Room to the latest alpha version, which lets us remove some workarounds from the source code as well as from the KSP configuration.

However, because of [CMP-5835](https://youtrack.jetbrains.com/issue/CMP-5835/Cannot-change-attributes-of-configuration-composeAppdebugFrameworkIosX64-after-it-has-been-locked-for-mutation) the Room plugin can't be applied at the moment.

### CODE REVIEW

**Comment by oreillyjf** [comment]
@zsmb13 sounded like this should work now (if I understand https://x.com/zsmb13/status/1831967820160151817 correctly)?

**Comment by zsmb13** [comment]
@joreilly The issue this was stuck on was [CMP-5835](https://youtrack.jetbrains.com/issue/CMP-5835/Cannot-change-attributes-of-configuration-composeAppdebugFrameworkIosX64-after-it-has-been-locked-for-mutation), which now has a workaround: applying AGP after other plugins (Kotlin, Compose, etc). Added this to the project, with this it should be ready to go.

This strict ordering eventually won't be required when https://github.com/JetBrains/compose-multiplatform/pull/5129 makes it into a release.

**Comment by joreilly** [comment]
Should `1.json` be needed here?

**Comment by zsmb13** [comment]
It's not strictly needed, but in a real project it would be committed to VCS. As the Room schema changes and the database version is updated, it'll generate `2.json` etc. Having these files records the history of the schemas over time to help with migrations.

**Pull request merged**
