### PR TITLE
Added a low fidelity player list loading screen

### PR DESCRIPTION
**Pull request by HoinzeyBear**
Added a low fidelity player list loading screen. This will be shown to user while we wait for players to finish loading and will change to the proper players list after.

This is a slightly clumsy version and could be refined if we think its a nice add. The sizings are a bit off especially if rotated to landscape or opened on a tablet. 

low-fidelity-players-list

### CODE REVIEW

**Comment by joreilly** [comment]
Looks good!  It possibly doesn't provide much more but might be interesting to see what https://google.github.io/accompanist/placeholder/ would offer....

**Comment by HoinzeyBear** [comment]
Only one way to find out ! Taking a look

**Comment by joreilly** [comment]
Yeah, seems like as you say small in memory list should be fine.

**Comment by HoinzeyBear** [comment]
Have pushed up changes using accompanist placeholder for both player list and the fixture list.

Also threw in the logic so that the fixture list will start at the current Gameweek rather than the first

**Comment by joreilly** [comment]
nice!

**Pull request merged**
